### ISSUE TITLE
[Bug] Trained DeltaNet can't decode token by token

### ISSUE THREAD

**Issue by Luther-Sparks** [fla-org/flame#27]
### Describe the Bug

I used `flame` to train a DeltaNet-400M. When testing the model, it can inference using `generate` interface. However, it can't inference by simply calling `model(**inputs)`.
Detailed information are below:
```python
prompt = "Hello, my name is"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda:0")
generated_text = ''
with torch.no_grad():
    # outputs = model.generate(**inputs, max_length=50, do_sample=False)    # this works fine
    # generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    for i in range(100):
        logits = model(**inputs, return_dict=True)    # this will cause an error.
        logits = logits.logits[:, -1, :]
        probs = torch.softmax(logits, dim=-1)
        next_token = torch.multinomial(probs, num_samples=1)
        inputs['input_ids'] = torch.cat([inputs['input_ids'], next_token], dim=1)
        generated_text += tokenizer.decode(next_token[0], skip_special_tokens=True)
print(generated_text)
```

Detailed error message is below:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[25], line 8
      4 with torch.no_grad():
      5     # outputs = deltanet.generate(**inputs, max_length=50, do_sample=False)
      6     # generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
      7     for i in range(100):
----> 8         logits = deltanet(**inputs, return_dict=True)
      9         logits = logits.logits[:, -1, :]
     10         probs = torch.softmax(logits, dim=-1)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.12/dist-packages/transformers/utils/deprecation.py:172, in deprecate_kwarg.<locals>.wrapper.<locals>.wrapped_func(*args, **kwargs)
    168 elif minimum_action in (Action.NOTIFY, Action.NOTIFY_ALWAYS) and not is_torchdynamo_compiling():
    169     # DeprecationWarning is ignored by default, so we use FutureWarning instead
    170     warnings.warn(message, FutureWarning, stacklevel=2)
--> 172 return func(*args, **kwargs)

File ~/flame/fla/models/delta_net/modeling_delta_net.py:370, in DeltaNetForCausalLM.forward(self, input_ids, attention_mask, inputs_embeds, past_key_values, labels, use_cache, output_attentions, output_hidden_states, return_dict, logits_to_keep, **kwargs)
    365 output_hidden_states = (
    366     output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
    367 )
    368 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
--> 370 outputs = self.model(
    371     input_ids=input_ids,
    372     attention_mask=attention_mask,
    373     inputs_embeds=inputs_embeds,
    374     past_key_values=past_key_values,
    375     use_cache=use_cache,
    376     output_attentions=output_attentions,
    377     output_hidden_states=output_hidden_states,
    378     return_dict=return_dict,
    379     **kwargs
    380 )
    382 hidden_states = outputs[0]
    383 fuse_linear_and_cross_entropy = self.config.fuse_cross_entropy and self.training

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File ~/flame/fla/models/delta_net/modeling_delta_net.py:240, in DeltaNetModel.forward(self, input_ids, attention_mask, inputs_embeds, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict, **kwargs)
    230     hidden_states, attentions, past_key_values = self._gradient_checkpointing_func(
    231         layer.__call__,
    232         hidden_states,
   (...)
    237         **kwargs
    238     )
    239 else:
--> 240     hidden_states, attentions, past_key_values = layer(
    241         hidden_states,
    242         attention_mask=attention_mask,
    243         past_key_values=past_key_values,
    244         use_cache=use_cache,
    245         output_attentions=output_attentions,
    246         **kwargs
    247     )
    249 if output_attentions:
    250     all_attns += (attentions,)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File ~/flame/fla/models/delta_net/modeling_delta_net.py:88, in DeltaNetBlock.forward(self, hidden_states, attention_mask, past_key_values, use_cache, output_attentions, **kwargs)
     86 residual = hidden_states
     87 hidden_states = self.attn_norm(hidden_states)
---> 88 hidden_states, attentions, past_key_values = self.attn(
     89     hidden_states=hidden_states,
     90     attention_mask=attention_mask,
     91     past_key_values=past_key_values,
     92     use_cache=use_cache,
     93     output_attentions=output_attentions,
     94     **kwargs
     95 )
     96 if self.config.fuse_norm:
     97     hidden_states, residual = self.mlp_norm(hidden_states, residual, True)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File ~/flame/fla/layers/delta_net.py:196, in DeltaNet.forward(self, hidden_states, attention_mask, past_key_values, use_cache, output_attentions, **kwargs)
    194         position_ids = prepare_position_ids(cu_seqlens)
    195     seq_idx = prepare_sequence_ids(position_ids).to(torch.int32).unsqueeze(0)
--> 196 q, conv_state_q = self.q_conv1d(x=self.q_proj(hidden_states),
    197                                 mask=conv_mask,
    198                                 cache=conv_state_q,
    199                                 output_final_state=use_cache,
    200                                 seq_idx=seq_idx)
    201 k, conv_state_k = self.k_conv1d(x=self.k_proj(hidden_states),
    202                                 mask=conv_mask,
    203                                 cache=conv_state_k,
    204                                 output_final_state=use_cache,
    205                                 seq_idx=seq_idx)
    206 v, conv_state_v = self.v_conv1d(x=self.v_proj(hidden_states),
    207                                 mask=conv_mask,
    208                                 cache=conv_state_v,
    209                                 output_final_state=use_cache,
    210                                 seq_idx=seq_idx)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /fla/modules/convolution.py:175, in ShortConvolution.forward(self, x, mask, cache, output_final_state, seq_idx)
    173 batch_size, _, hidden_size = x.shape
    174 if mask is not None:
--> 175     x = x.mul_(mask.unsqueeze(-1))
    176 if output_final_state and cache is None:
    177     cache = x.new_zeros(batch_size, hidden_size, self.kernel_size[0])

RuntimeError: The size of tensor a (7) must match the size of tensor b (6) at non-singleton dimension 1
```

### Steps to Reproduce the Bug

**config**
[delta_net_400M.json](https://github.com/user-attachments/files/19869480/delta_net_400M.json)

**delta_net-400M-10B.toml**
```toml
[model]
config = "configs/delta_net_400M.json"
tokenizer_path = "~/checkpoints/Llama-3.2-hf/Llama-3.2-1B/"

[job]
dump_folder = "exp/delta_net-400M-10B/batch8.seqlen8192.warmup1024.update1.steps20480.lr1e-3"
print_args = true

[training]
batch_size = 8
seq_len = 8192
context_len = 2048
gradient_accumulation_steps = 1
steps = 20480
max_norm = 1.0
skip_nan_inf = true
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "~/dataset/fineweb/"
dataset_name = "default"
num_workers = 24
pin_memory = false
persistent_workers = false
prefetch_factor = 2
seed = 42
varlen = false

[optimizer]
name = "AdamW"
eps = 1e-15
lr = 1e-3

[lr_scheduler]
warmup_steps = 1024
decay_type = "cosine"
lr_min = 0.1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 200
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"    # ["disabled", "async", "async_with_pinned_mem"]

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 512

[metrics]
log_freq = 10
enable_tensorboard = true

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false

[activation_checkpoint]
mode = "none"
```

**training script**
```sh
NNODE=1 NGPU=8 LOG_RANK=0 bash train.sh \
  --job.config_file configs/delta_net-400M-10B.toml \
  --job.dump_folder exp/delta_net-400M-10B/batch8.seqlen8192.warmup1024.update1.steps20480.lr1e-3 \
  --model.config configs/delta_net-400M.json \
  --model.tokenizer_path ~/checkpoints/Llama-3.2-hf/Llama-3.2-3B/
```

### Expected Behavior

I expect it managing to generate tokens one by one.

### Environment Information

1. Torch: 2.7.0
2. Triton: 3.2.0
3. Python: 3.12.3
4. cuda: 12.8
